apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:global-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bitbucket.org/eniogmbh/infrastructure-helmchart-global-resources.git
    targetRevision: HEAD
    path: chart
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
